# -*- coding: utf-8 -*-
"""experiment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ID6q-SAZ8isxUVbLGu6WfwhTkq8m4ag1
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
data = [10, 12, 13, 15, 20, 28, 29, 102, 90]
plt.boxplot(data)

out = []
threshold = 1
mean = np.mean(data)
sd = np.std(data)

for i in data:
    z = (i - mean)/sd
    print(f"Element {i} : {z}")

    if np.abs(z) > threshold:
        out.append(i)

print(out)

sort = sorted(data)
q1, q3 = np.percentile(sort, [25, 75])
print(q1, q3)
inter = q3 - q1
print(inter)
upper = q3 + (1.5 * inter)
lower = q1 - (1.5 * inter)
print(upper, lower)

remove = []

for i in sort:
    if ((i > upper) | (i < lower)):
        remove.append(i)

print(remove)

